# Generated by Django 5.0.2 on 2024-02-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scribe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='title',
        ),
    ]
