# Generated by Django 4.1.3 on 2024-03-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scribe', '0002_remove_text_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
